# Generated by Django 3.0.8 on 2020-07-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsignaturemodel',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
