# Generated by Django 3.0.8 on 2020-07-16 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_date', models.DateTimeField(auto_now=True)),
                ('client_signature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='joey.JSignatureModel')),
            ],
        ),
    ]
