# Generated by Django 3.0.8 on 2020-07-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joey', '0002_consultation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100, null=True)),
                ('client_temp', models.IntegerField()),
                ('has_mask', models.BooleanField(default=False, null=True)),
                ('covid_diagnosed', models.BooleanField(default=False, null=True)),
                ('covid_test_type', models.TextField(null=True)),
                ('covid_test_date', models.DateTimeField(null=True)),
                ('covid_test_results', models.TextField(null=True)),
                ('has_symptoms', models.BooleanField(default=False, null=True)),
                ('has_been_to_high_risk_zone', models.BooleanField(default=False, null=True)),
                ('has_close_contact_with_suspect', models.BooleanField(default=False, null=True)),
                ('is_clinically_vulnerable', models.BooleanField(default=False, null=True)),
                ('has_vulnerable_disease', models.BooleanField(default=False, null=True)),
                ('self_quarantine', models.BooleanField(default=False, null=True)),
                ('has_traveled', models.BooleanField(default=False, null=True)),
                ('client_questions', models.TextField(null=True)),
                ('report_agreement', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
