# Generated by Django 3.0.8 on 2020-07-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joey', '0002_jsignaturemodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsignaturemodel',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jsignaturemodel',
            name='signature_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Signature date'),
        ),
    ]
