# Generated by Django 3.0.8 on 2020-07-14 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joey', '0003_auto_20200714_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsignaturemodel',
            name='name',
        ),
    ]
