# Generated by Django 3.0.8 on 2020-08-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joey', '0003_questionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='had_symptoms',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
